import { getToken } from "./getToken";

export async function getGroups() {
  return fetch(
    'https://sau-portal.de/team-11-api/api/v1/group?withDetails=false',
    {
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${getToken()}`,
      },
    }
  )
    .then((response) => response.json())
    .then((data) => {
      return data;
    })
    .catch((error) => {
      console.error('Error fetching study groups:', error);
      return [];
    });
}

/*
  return {
    group_count: 5,
    groups: [
      {
        name: 'string',
        students_count: 1,
        students: [
          {
            uuid: '8835a06d-79d2-44f6-94c3-6f123503e352',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'string',
            degreeProgram: 'string',
            semester: 1,
            studyStatus: 'ENROLLED',
            cohort: 'string',
            address: 'string',
            phoneNumber: '- 80-98',
            dateOfBirth: '2015-10-20',
          },
        ],
      },
      {
        name: 'BIN-T23-F4',
        students_count: 31,
        students: [
          {
            uuid: 'b7acb825-4e70-49e4-84a1-bf5dc7c8f509',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: '123456',
            degreeProgram: 'Computer Science',
            semester: 1,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Test Address 1',
            phoneNumber: '123456789',
            dateOfBirth: '2000-01-01',
          },
          {
            uuid: '932b14ae-0d62-4c0e-98db-5a1c63a741e5',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_1',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000011',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'dbfa6393-5d22-47cd-862d-7130d0d4a2d3',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_2',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000012',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'f14aef21-eb6e-49c7-a466-6378cdd2f67c',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_3',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000013',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '5cfc16c6-dd11-4150-a0a3-e8eb1e2d79a7',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_4',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000014',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '0d0be51d-24ef-4b21-8062-82044aedb482',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_5',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000015',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'a008de82-abe1-49e4-b563-fa5b3ee070ff',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_6',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000016',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '082bbe0d-32c6-4763-9013-76568ded6f65',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_7',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000017',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '8af01469-ddca-4c60-b1bf-8569381ba6e1',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_8',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000018',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '5f9c769c-2dd7-44da-9a6a-cdb4947bf2dd',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_9',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000019',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '5d2636b1-d583-4351-8f9f-7514d92cbb5f',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_10',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000020',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '03774dbc-6beb-447d-99cc-f10512bb4b68',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_11',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000021',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'daea04d4-d4a9-4c7d-93d0-4940a7450f39',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_12',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000022',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'eeedc84e-4cb1-45da-a4b1-5305f360701f',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_13',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000023',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'e0c89731-4d30-463b-ae1b-5527af31af18',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_14',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000024',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '34297ea2-4159-4ae9-9a94-ee750d11090c',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_15',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000025',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '210b953c-9939-4521-8bc5-9527da3ff665',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_16',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000026',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '1551d4c4-1ba6-4a2b-bb23-1ee619cedcf6',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_17',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000027',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '7e444437-fdee-4f4d-b409-7b57f40baf74',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_18',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000028',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '2db40ddc-7d2d-423c-97f8-7fd5e25b6dbb',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_19',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000029',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '20abbcf8-4113-4421-9004-e766a312b4aa',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_20',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000030',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'cb23d2a9-d9a9-4378-9362-9949d422bd5b',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_21',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000031',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '316dcfc2-2dec-49c9-ae8e-edb513068565',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_22',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000032',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '6ac0b85b-42c0-43a8-a8c5-2df58ed94f63',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_23',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000033',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '59258f08-94cb-4bd9-8977-800a6cfa66fe',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_24',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000034',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '40fb21fe-4ca0-41e0-af0e-7fba1de61fcc',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_25',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000035',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '6628bd62-5f6b-4302-8476-7ff90a2f7cb5',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_26',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000036',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '91f0563b-196b-45e5-88a4-c68f2f405d58',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_27',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000037',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'd6b2e3e0-0f0d-489f-a0ea-5da3f3803bda',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_28',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000038',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: '56597498-4497-4ff5-b497-eb97017e06a3',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_29',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000039',
            dateOfBirth: '2002-01-01',
          },
          {
            uuid: 'c2b86b8b-6d2e-4dba-b321-40cb46a80024',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g1_30',
            degreeProgram: 'Computer Science',
            semester: 2,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F4',
            address: 'Some Address',
            phoneNumber: '+4915100000040',
            dateOfBirth: '2002-01-01',
          },
        ],
      },
      {
        name: 'BIN-T23-F2',
        students_count: 10,
        students: [
          {
            uuid: '6769b30f-6094-424a-9be4-5246a20ffa64',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_11',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000051',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'e45c1456-1d00-410e-815d-556087a35503',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_12',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000052',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'd5cf51ae-f1e5-4eaf-84c0-fe144b7a8203',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_13',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000053',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'a614aa19-8abe-4751-8c4d-c1f276154099',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_14',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000054',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '47d6ad25-7617-4eb6-8cd9-22a31be5547b',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_15',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000055',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '5f60978e-032e-42e3-8b85-c8b6b820bcb1',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_16',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000056',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'dbbb9dfe-0d05-426c-b040-0503754cc501',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_17',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000057',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '30b6c66c-dbd0-4946-958e-ae49d50313ba',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_18',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000058',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '36fe8460-80f4-4170-be0e-6e2440903427',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_19',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000059',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '7381029c-1201-4d0e-8899-65a15dc09df8',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_20',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F2',
            address: 'Some other Address',
            phoneNumber: '+4915100000060',
            dateOfBirth: '2003-01-01',
          },
        ],
      },
      {
        name: 'BIN-T23-F3',
        students_count: 10,
        students: [
          {
            uuid: 'f4527a3e-05b6-4e63-b0f6-35047695bf9b',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_21',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000061',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '6c479128-ea66-4202-93b0-00fa469a8158',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_22',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000062',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '546dbf06-9247-4cbb-b949-12970bfe2d9a',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_23',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000063',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'ef219d81-8b9c-4a8b-a18b-c27e7a699e42',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_24',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000064',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '986b0120-fe35-4039-99ca-5a7f909cb759',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_25',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000065',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'bd4b51da-481a-4ccc-843d-0c241831acb3',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_26',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000066',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '9161af4f-d65e-4229-848e-cc6fa16f8cf5',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_27',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000067',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '5fd4679d-3d4a-4845-bfbf-5be9f686e82c',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_28',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000068',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '78315bf6-1450-4999-8090-c79ed9b63a40',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_29',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000069',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '4576ca20-9927-4219-b106-a1cb1f3dd537',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_30',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F3',
            address: 'Some other Address',
            phoneNumber: '+4915100000070',
            dateOfBirth: '2003-01-01',
          },
        ],
      },
      {
        name: 'BIN-T23-F1',
        students_count: 10,
        students: [
          {
            uuid: 'e1f908c1-c57e-439a-9ddd-f38722931298',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_1',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000041',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'f71d2603-9a2f-4761-bb1e-31e81d31c692',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_2',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000042',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '8a172f8e-cdd1-4dd7-bf9a-914c4dad3da3',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_3',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000043',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '9d7ebe36-4beb-4119-8dfd-5a3d606a4a68',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_4',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000044',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '07d2afc7-639c-43cc-857f-5e9f70d8efc7',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_5',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000045',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '1339dbf4-4e12-4aab-a8ec-5c0cce84a02d',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_6',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000046',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: 'd7b55eec-c516-4777-b456-e440b185467c',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_7',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000047',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '7720f0c4-9612-42ff-ad06-744e571f6fde',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_8',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000048',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '4633690d-4a79-488c-bd2d-89f32d4eafad',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_9',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000049',
            dateOfBirth: '2003-01-01',
          },
          {
            uuid: '1ee303bd-f268-4633-936f-d0e2148566a6',
            firstName: null,
            lastName: null,
            username: null,
            email: null,
            matriculationNumber: 'm_g2_10',
            degreeProgram: 'Business Informatics',
            semester: 4,
            studyStatus: 'ENROLLED',
            cohort: 'BIN-T23-F1',
            address: 'Some other Address',
            phoneNumber: '+4915100000050',
            dateOfBirth: '2003-01-01',
          },
        ],
      },
    ],
  };
}
*/
